version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: mern-template-db-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - mern-network-dev

  # Backend Server (Development)
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mern-template-server-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mern-template-dev?authSource=admin
      - PORT=5000
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    depends_on:
      - mongodb
    networks:
      - mern-network-dev
    command: npm run dev

volumes:
  mongodb_data_dev:

networks:
  mern-network-dev:
    driver: bridge
