version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: mern-template-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

  # Backend Server
  server:
    build: .
    container_name: mern-template-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mern-template?authSource=admin
      - PORT=5000
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - mern-network

  # Frontend (for production)
  nginx:
    image: nginx:alpine
    container_name: mern-template-nginx
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - mern-network

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge
